### ISSUE TITLE
Console crashes after certain point in Super Mario Odyssey 

### ISSUE THREAD

**Issue by FreepDryer** [AnalogMan151/FreeShopNX#3]
No error provided, hard crash with only exit of force shutdown.

**Comment by FreepDryer** [comment]
Happens from transfer to metro kingdom from lost kingdom.

**Comment by ctxnop** [comment]
I really don't think that this software is related to your issue. Either the game is downloaded, either it's not. This software doesn't do anything else. It may be related to the custom firmware you use, or something like that.

**Comment by ctxnop** [comment]
I don't known if there is any issue using that, I'm saying that you should probably ask your CFW's developer rather than the developer of FreeShopNX. Because this software is not responsible of running titles, it just downloads them. Then, an other software install the title, and a third one run it. Because of this, it means that if you have an in-game issue, the most relevant responsible is the game it-self (nintendo in your case), then the game runner (the CFW), then the game installer (tinfoil probably, not sure about this one, because I didn't dig enough into this software's code to be sure), then the game downloader (this software).

**Comment by FreepDryer** [comment]
Okay, I’ll contact hekate’s developer and ask if there is an issue there. Thank you for the response.
